// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW46gTm4JzBtM6ZxuETbXrrCa5PpVfltE',
    appId: '1:371034844067:web:bc3aa5a5d941007d3c0816',
    messagingSenderId: '371034844067',
    projectId: 'phize-de7a1',
    authDomain: 'phize-de7a1.firebaseapp.com',
    storageBucket: 'phize-de7a1.firebasestorage.app',
    measurementId: 'G-PCJ8679956',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtJNTiev7tyrOQ_Q46deGrTsO5kg1V52M',
    appId: '1:371034844067:android:cb7b5bcd4475bb613c0816',
    messagingSenderId: '371034844067',
    projectId: 'phize-de7a1',
    storageBucket: 'phize-de7a1.firebasestorage.app',
  );
}
